export enum PermissionFlag {
    BASIC_USER_PERMISSION = 1,
    AUTHOR_PERMISSION = 2,
    EVENT_PRODUCER_PERMISSION = 4,
    MODERATOR_PERMISSION = 8,
    ADMIN_PERMISSION = 16,
    ALL_PERMISSIONS = 2147483647,
}